services:
  configserver:
    build:
      context: .
      dockerfile: configserver/Dockerfile
    ports:
      - 8888:8888
    networks:
      - microservice-networks
    environment:
      - GIT_KEY=${GIT_KEY}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 2
      start_period: 60s
  discoverserver:
    build:
      context: .
      dockerfile: discoverserver/Dockerfile
    ports:
      - 8761:8761
    depends_on:
      configserver:
        condition: service_healthy
    networks:
      - microservice-networks
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 2
      start_period: 60s

networks:
  microservice-networks:
    driver: bridge
