apiVersion: apps/v1
kind: Deployment
metadata:
  name: discoverserver
  labels:
    app: discoverserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: discoverserver
  template:
    metadata:
      labels:
        app: discoverserver
    spec:
      containers:
      - name: discoverserver
        image: eventsourcing-discoverserver
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8761

---
apiVersion: v1
kind: Service
metadata:
  name: discoverservice
spec:
  selector:
    app: discoverserver
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: NodePort
