server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes: #mapping service route
            - id: employeeservice
              uri: lb://employeeservice # lb: load balancing
              predicates:
                - Path=/api/v1/employees/**

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true # Register with eureka to know all the ports of the instances of a service