server:
  port: 8080

spring:
  application:
    name: gateway-service
  data:
    redis:
      port: 6379
      host: localhost
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes: #mapping service route
            - id: employeeservice
              uri: lb://employeeservice # lb: load balancing
              predicates:
                - Path=/api/v1/employees/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10 # in 1s refill 10 tokens
                    redis-rate-limiter.burstCapacity: 20 # maximum in bucket has 20 tokens
                    redis-rate-limiter.requestedTokens: 1 # 1 request use 1 token

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true # Register with eureka to know all the ports of the instances of a service