server:
  port: 9005

spring:
  application:
    name: borrowingservice
  datasource:
    url: jdbc:h2:mem:borrowingDB
    username: sa
    password: 123456
    driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
  config:
    import: "optional:configserver:"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/