# spring:
#   application:
#     name: bookservice
#   datasource:
#    url: jdbc:mysql://localhost:3307/bookdb
#    username: root
#    password:
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#
#   mail:
#     host: smtp.gmail.com
#     port: 587
#     username: ngocbach.selfstudy1@gmail.com
#     password: yulc dhlu bpbe dkmv
#     properties:
#       mail:
#         smtp:
#           auth: true
#           starttls:
#             enable: true
#         transport:
#           protocol: smtp
#   config:
#     import: "optional:configserver:"

# server:
#   port: 9002

# eureka:
#   client:
#     serviceUrl:
#       defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

# axon:
#   axonserver:
#     servers: axonserver:8124

spring:
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: "configserver:"
  application:
    name: bookservice-application