#spring:
#  application:
#    name: bookservice
#  datasource:
#    url: jdbc:h2:mem:bookDB
#    username: sa
#    password: 123456
#    driverClassName: org.h2.Driver
#    jpa:
#      database-platform: org.hibernate.dialect.H2Dialect
#  h2:
#    console:
#      enabled: true
#  jpa:
#    hibernate:
#      ddl-auto: update
#
#server:
#  port: 9002
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: "configserver:"
  application:
    name: bookservice-application