# spring:
#   application:
#     name: bookservice
#   datasource:
#     url: jdbc:h2:mem:bookDB
#     username: sa
#     password: 123456
#     driverClassName: org.h2.Driver
#     jpa:
#       database-platform: org.hibernate.dialect.H2Dialect
#   h2:
#     console:
#       enabled: true
#   jpa:
#     hibernate:
#       ddl-auto: update
#   mail:
#     host: smtp.gmail.com
#     port: 587
#     username: ngocbach.selfstudy1@gmail.com
#     password: yulc dhlu bpbe dkmv
#     properties:
#       mail:
#         smtp:
#           auth: true
#           starttls:
#             enable: true
#         transport:
#           protocol: smtp
#   config:
#     import: "optional:configserver:"

# server:
#   port: 9002

# eureka:
#   client:
#     serviceUrl:
#       defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

# axon:
#   axonserver:
#     servers: axonserver:8124

spring:
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: "configserver:"
  application:
    name: bookservice-application